---
cluster:
  name: bramble
  id: 1
bgp:
  enabled: false
l2announcements:
  enabled: true
  leaseDuration: 120s
  leaseRenewDeadline: 60s
  leaseRetryPeriod: 1s
k8sServiceHost: 192.168.2.221
k8sServicePort: 6443
rollOutCiliumPods: true
localRedirectPolicy: true
kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
loadBalancer:
  algorithm: maglev
  mode: dsr
bandwidthManager:
  enabled: true
  bbr: true
bpf:
  masquerade: true
  tproxy: true
l7Proxy: true
enableCnpStatusUpdates: true
endpointStatus:
  enabled: true
  status: "policy"
ipam:
  mode: "kubernetes"
ingressController:
  enabled: true
  default: true
  loadbalancerMode: shared
operator:
  rollOutPods: true
autoDirectNodeRoutes: true
ipv4NativeRoutingCIDR: 10.244.0.0/16
tunnel: "disabled"
containerRuntime:
  integration: containerd
hubble:
  enabled: true
  serviceMonitor:
    enabled: false
  metrics:
    enabled:
      - dns:query;ignoreAAAA
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http
  relay:
    enabled: true
    rollOutPods: true
  ui:
    enabled: true
    ingress:
      enabled: true
      className: cilium
      hosts:
        - hubble.lan
    rollOutPods: true
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
