creation_rules:
  - encrypted_regex: '^(data|stringData|caBundle)$'
    path_regex: 'cluster/.*\.sops\.ya?ml$'
    age: >-
      age1s4gf4qkcuy5t3ksgupe7q8hyesmemtvnvafa9nkpfzc3zewl9q4q33qjfm
  - path_regex: 'talos/.*\.sops\.ya?ml$'
    age: >-
      age1s4gf4qkcuy5t3ksgupe7q8hyesmemtvnvafa9nkpfzc3zewl9q4q33qjfm
  - path_regex: '.*-secret\.sops\.ya?ml$'
    age: >-
      age1s4gf4qkcuy5t3ksgupe7q8hyesmemtvnvafa9nkpfzc3zewl9q4q33qjfm