---
version: "3"

vars:
  CLUSTER_DIR: "{{.ROOT_DIR}}/cluster"
  TALOS_DIR: "{{.ROOT_DIR}}/talos"

env:
  KUBECONFIG: "{{.ROOT_DIR}}/kubeconfig"
  SOPS_AGE_KEY_FILE: "/Users/josiah/Library/Application/Support/sops/age/keys.txt"

includes:
  talos: .taskfiles/talos.yml

tasks:
  default:
    silent: true
    cmds: ["task -l"]