---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-minio
  namespace: flux-system
spec:
  path: ./cluster/apps/storage/minio/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: bramble-iac
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
