---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: directpv
  namespace: storage
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: ./operator/helm-charts/directpv-chart
      version: v4.0.9
      sourceRef:
        kind: GitRepository
        name: directpv
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
