---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: louislam/uptime-kuma
              tag: 1.23.7
            env:
              TZ: "America/Chicago"
    service:
      main:
        ports:
          http:
            port: 3001
    ingress:
      main:
        enabled: true
        className: cilium
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          kubernetes.io/tls-acme: "true"
        hosts:
          - host: &host uptime.hutchinson.house
            paths:
              - path: "/"
                pathType: "Prefix"
                service:
                  name: main
        tls:
          - hosts:
              - *host
            secretName: uptime-tls
    persistence:
      data:
        enabled: true
        globalMounts:
          - path: /app/data
        storageClass: ceph-block
        accessMode: ReadWriteOnce
        size: 30Gi
        retain: true