---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homer
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: homer
      version: 6.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: b4bz/homer
      tag: 21.07.1
      pullPolicy: IfNotPresent
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
          - host: "homer.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "homer.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: homer-config
        mountPath: /www/assets
    configmap:
      enabled: true
      config: |
        title: "Bramble Dashboard"
        subtitle: "Raspberry Pi Cluster Applications"
        header: true
        footer: false
        connectivityCheck: true
        columns: "5"
        theme: default
        links:
          - name: "Bramble IAC Repo"
            icon: "fab fa-github"
            url: "https://github.com/ground7/bramble-iac"
            target: "_blank"
        services:
          - name: "Devices"
            icon: "fas fa-storage"
            items:
              - name: "Longhorn"
                tag: "device"
                url: "https://longhorn.${SECRET_DOMAIN}"
                target: "_blank"