---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-uptime-kuma
  namespace: flux-system
spec:
  path: ./cluster/apps/monitoring/uptime-kuma/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: bramble-iac
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
