---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: policy
spec:
  loadBalancerIPs: true
  interfaces:
    - ^enx.*
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
