---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: descheduler
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/descheduler
      chart: descheduler
      version: 0.21.0
      sourceRef:
        kind: HelmRepository
        name: descheduler-charts
        namespace: flux-system
      interval: 5m
  values:
    kind: Deployment
    image:
      repository: k8s.gcr.io/descheduler/descheduler
    resources:
      requests:
        cpu: 500m
        memory: 256Mi
    cronJobApiVersion: "batch/v1beta1"  # Use "batch/v1beta1" for k8s version < 1.21.0. TODO(@7i) remove with 1.23 release
    schedule: "*/2 * * * *"
    deschedulingInterval: 5m
    deschedulerPolicy:
      strategies:
        RemoveDuplicates:
          enabled: true
        RemovePodsViolatingNodeTaints:
          enabled: true
        RemovePodsViolatingNodeAffinity:
          enabled: true
          params:
            nodeAffinityType:
            - requiredDuringSchedulingIgnoredDuringExecution
        RemovePodsViolatingInterPodAntiAffinity:
          enabled: true
        LowNodeUtilization:
          enabled: false