---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.3.0
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
  values:
    defaultSettings:
      backupTarget: s3://longhorn-backup@us-east-1/
      backupTargetCredentialSecret: minio-secret
      createDefaultDiskLabeledNodes: true
      defaultDataPath: "/storage"
      defaultDataLocality: best-effort
      systemManagedComponentsNodeSelector: node-role.kubernetes.io/worker=true
    longhornManager:
      nodeSelector: 
        node-role.kubernetes.io/worker: "true"
    longhornDriver:
      nodeSelector: 
        node-role.kubernetes.io/worker: "true"
    ingress:
      enabled: true
      host: longhorn.${SECRET_DOMAIN}
      ingressClassName: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"       
        traefik.ingress.kubernetes.io/router.middlewares: longhorn-system-svc-longhorn-headers@kubernetescrd
        hajimari.io/enable: "true"
        hajimari.io/icon: "cow"
        hajimari.io/appName: "longhorn"
      rules:
      - http:
          paths:
          - path: /
            backend:
              serviceName: longhorn-frontend
              servicePort: 80
