# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:2wShgQTMh03H4vOrJ5FFUfBstUk1h7etcaC0th2VYgqrVB2gk++Szw==,iv:ZS2d7e3AQgVW+CiftckaXEbO/Pa49GbR6bi9/iz3Rnk=,tag:JLCmjzgDA8lR0W9Qj5i2mA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-26T15:55:59Z"
    mac: ENC[AES256_GCM,data:IdqZvbfbanRYul49cB2sk9A8x1jy4uU6+wzGiusb7rAwICfe50yvXHJv9A5ZEDt4WGubk0Ojv0obJxuU+UVV/ROlgISF7jgEZbv1H09vjZ+t9hkZOJB3Q22H0//cV3DMU9uqGRsxkNR5iYNmsFlNl6AZNazS75i+nCcJagvhijY=,iv:XDyc+5xyEGAK3WvBPjq2yHwDNHao0VzuemAeYR/jcMo=,tag:XTETcC1WMnCTm2zeNs90MA==,type:str]
    pgp:
        - created_at: "2021-08-26T15:55:58Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA94M1f6SPVxmARAAxaMqk3pi3nKLs+6kxhQ2vcjQkHOV2ePD+EqTc+qFXCCx
            qY/yfw4P4Ym1OP0O5uhh2lv0QPl3j1FSATNQNtzzubqCydFfGBRv4mPZuDD336oZ
            heOM8snySxbr1THoOIIWmGron5h3lsO/F9asYeb/9oHwIbb4JnQ4dx3sMIIMb2sw
            dcZmMrsRw92iNOQsfxa6d9ZRjP+A7LYfrzj7eYq/0+PkEUdyU/NqsSn/YCyIVuSP
            JArrFE83gfWyjfsSxBgPOChLqDdDgJRp/pXtpxdPuNRDDPPvEfaf6lFpCMVadCEe
            pkl0aUy0xob5n9pl2lqLB/b1m3twmnuMYEg+IR9kkcfLV3EKOS8KKEyKq2jM8hLC
            zyBvEp05dcYdf1tySs7aYDnqBJT3iCFE/gEuGqH8JkHpa0S6MVR/dosIRcH9xG3S
            IrmsekwBkpq/KCau5X8/by/Yv1uFXAPXqQLKdL7g4QsfdyuO6YrGXkdRNvW4NjRs
            fgDuZqFKmsg6xo/54S7jooUYJzv8QmagpAMMiAbI0s+HZ48tXH9XroawC/ABfSeT
            ORgUL79oyBR9qiCt2ZME00JCojKrKA/I7xPDhA4G0H5AM48wGls+mQUKDxLknC7j
            uVvniwCaaR7whuk56PzB5JtusXcWMKFS66G6/rCKyRF96xdM4cde2Dj9ik51dBjS
            XAGa46n2JkPz+wkUdtvJUmbJ7hNReJ+jJo1VA61teGlIXEBjKwYhQylousUrC5Ql
            uNnnP8e9KhfrKQmE0MaM+JH5VHAppZ9PhGLG17kAKRFzLxXJs3EmX/OxYMdk
            =yDY5
            -----END PGP MESSAGE-----
          fp: 1DD4ABC83CD871B6ED7C66D6282DC0E780A9C001
        - created_at: "2021-08-26T15:55:58Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA02OywL/+sGsAQ/+PhKk2pMcl3epkYK7X6Vw+eEQpXs9GWMQv9ejjCVGlmqC
            jbkMPV/0wvZmr+zGY5A5SN/N6EF3HL5MNo10TPCoLrd/WhnENcKxPnlcX0V8kgnn
            Yio37fkD1QUn6MG0Jb7EmHSWclPt+C9vSGxMfPTyjmUiq3yzCWL6pv/wvf+CIZZy
            Nt5/DjxfpDn4HG05CLx9cQk5EyNLttQOly8jAd418kWForCR+GkfFBXyLb1owxW+
            wO3jtl2JWna4rC7J5eNlgXHFFdGBzd3fb050qRZ/kw5m60rHhCm1eIL90eqvwZeB
            g/UOyyNIB+mMQ/k/FB8Ghm9eOyOIrd8CFXfvxlpymtVAj9guIYbSejAwt7LchZeY
            tUaETYXXXVr7bwZ1Gcly5QMfXz9wpF0j+XbmbdgUTAIt7yooYmN1MAV+VOaZDJfY
            tt9vBEzOLrHIasNs3dq+YvV7mjV4yz/i4NSv0eeHP/QtcayJRvfcG5boTzFc7g5U
            xR3WIOxU3CFAmSbCbz0PnNuQwgLIB5zVy+KHIoMY/lcLSr4o89Yxe7SiiXDELsv0
            UEC43ma3sXalerwdedSM+gWgbMiRVjnK8OACT0Sof7lY89+WHnTdXQf6qdcJWkQp
            Wv7wJ9QgRsmyFjiCxYZkaQbHUEg7LXiNGAnPZ+RGNR6mV5kRMfEmiH9ERzlEiYrS
            XAGuKz7tXOLNK5g2a6x5PLgCZC1oMwxHhKqrFPdLIcnyRuHJ6Nn80vqirpr6qwEz
            /Ri24tkLgclUYKT6OM8YCB9JJ4VNN6+5IVapqOUeOalvDrrSuOJbo5VWatxc
            =pQn+
            -----END PGP MESSAGE-----
          fp: 572C00D8FD4A214E08C0B0B76216E574F9CE6864
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
