---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ground7@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email: ground7@gmail.com
            apiKeySecretRef:
              name: cloudflare
              key: apikey
        selector:
          dnsZones:
            - hutchinson.house
